package de.devin.pipesnphysics.physics;

/**
 * Describes a pipe that should burst due to overpressure.
 * Generated by the solver, processed by the handler layer.
 *
 * @param node the pipe node that is overpressured
 * @param pressure the actual pressure at the node
 * @param threshold the burst threshold that was exceeded
 */
public record BurstEvent(NodeId node, float pressure, float threshold) {}
